#image: alpine:3.4
image: agileware/python-3.6.1-node-6.11

before_script:
  - pip install pycodestyle flake8 flake8-docstrings
  - npm install -g eslint
  - pwd
  - ls -l

test:
  script:
  - flake8
  - eslint assets
  allow_failure: false

