version: '2.3'
services:
  db:
    container_name: ${CONTAINER_DATABASE_NAME}
    image: mysql:5.7.23
    ports:
      - "127.0.0.1:${MYSQL_GLOBAL_PORT}:${MYSQL_PORT}"
    volumes:
      - "${MYSQL_VOLUME}:/var/lib/mysql"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: unless-stopped
  app:
    container_name: ${CONTAINER_APP_NAME}
    runtime: ${runtime}
    build:
      context: .
      network: host
    networks:
      - default
      - web
    ports:
      - "${VIRTUAL_HOST}:${APP_HTTP_PORT}:8000"
      - "${VIRTUAL_HOST}:${NOTEBOOK_HTTP_PORT}:8001"
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PROTO=uwsgi
# Uncomment below to DELETE and re-create the database from fixtures
#      - RESET_DB=true
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./user_data:/code/user_data
      - ./backups:/code/backups
  cache:
    image: redis
    container_name: ${CONTAINER_CACHE_NAME}
    restart: unless-stopped
networks:
  web:
    external:
      name: ${EXTERNAL_NETWORK}
